# 正常登录
url: "http://apis.imooc.com/api/user/login"
body:
  email: "111@test.com"
  password: "111111"
  icode: "042D5F8F2ECD35C3"
expect:
  code: 0
  msg: "请求成功"
---
# 登录密码为空
url: "http://apis.imooc.com/api/user/login"
body:
  email: "111@test.com"
  password: ""
  icode: "042D5F8F2ECD35C3"
expect:
  code: 422
  error: "Validation Failed"
  detail:
    message: "should not be empty"
    code: "invalid"
    field: "password"